### ISSUE TITLE
Crash after using Drones

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1006]
It happened with MotherShip ones, but probably happens with Drone Ship's too. Below is the crash log:

```
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 871
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 882
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in OpenHV/engine/OpenRA.Mods.Common/Activities/Air/Land.cs:line 236
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.Enter.Tick(Actor self) in OpenHV/engine/OpenRA.Mods.Common/Activities/Enter.cs:line 140
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in OpenHV/engine/OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in OpenHV/engine/OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

**Comment by dnqbob** [comment]
Do you have the replay? that will be helpful on debugging.

**Comment by WilliamWeberBerrutti** [comment]
I'll see if I can record a replay ASAP.

**Comment by WilliamWeberBerrutti** [comment]
Got the replay for you!

[hv-2024-07-24T214350Z - Mothership Crash.orarep.tar.gz](https://github.com/user-attachments/files/16367797/hv-2024-07-24T214350Z.-.Mothership.Crash.orarep.tar.gz)

Branch: https://github.com/WilliamWeberBerrutti/OpenHV/tree/CrashInvestigationMotherShip

**Comment by dnqbob** [comment]
kk, I will apply CA's method first to see if it fixes the crash in replay.

**Comment by dnqbob** [comment]
```
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key 'builder2' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Traits.ProductionQueue.ResolveOrder(Actor self, Order order) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Mods.Common\Traits\Player\ProductionQueue.cs:line 405
   at OpenRA.Actor.ResolveOrder(Order order) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Actor.cs:line 430
   at OpenRA.Network.UnitOrders.ResolveOrder(Order order, World world, OrderManager orderManager, Int32 clientId) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\UnitOrders.cs:line 366
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\UnitOrders.cs:line 350
   at OpenRA.Network.OrderManager.ProcessOrders() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\OrderManager.cs:line 244
   at OpenRA.Network.OrderManager.TryTick() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\OrderManager.cs:line 314
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Launcher\Program.cs:line 32
```

**Comment by dnqbob** [comment]
![捕获](https://github.com/user-attachments/assets/4aed6ad8-e544-46b2-9b8f-140a90a60247)


```
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key 'builder2' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Traits.ProductionQueue.ResolveOrder(Actor self, Order order) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Mods.Common\Traits\Player\ProductionQueue.cs:line 405
   at OpenRA.Actor.ResolveOrder(Order order) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Actor.cs:line 430
   at OpenRA.Network.UnitOrders.ResolveOrder(Order order, World world, OrderManager orderManager, Int32 clientId) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\UnitOrders.cs:line 366
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\UnitOrders.cs:line 350
   at OpenRA.Network.OrderManager.ProcessOrders() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\OrderManager.cs:line 244
   at OpenRA.Network.OrderManager.TryTick() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Network\OrderManager.cs:line 314
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\OpenHV-test\engine\OpenRA.Launcher\Program.cs:line 32
```

**Comment by dnqbob** [comment]
My bad, wrong branch

**Comment by dnqbob** [comment]
![无标题](https://github.com/user-attachments/assets/caa6693d-45f9-4ded-a0b0-8c50648b946d)
Fix confirm on this issue by using [CA's method](https://github.com/Inq8/CAmod/commit/c6a348284f16d449ac1d5659ab6dd2fcc883e8e4). Replay pause on the last frame and the game is not crashed.

**Comment by Mailaender** [comment]
Looks like I gave up too early. Thanks to both of you for the short replay and the on point investigation!
