### ISSUE TITLE
Crash after attacking with Planes

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1060]
We were playing on my MotherShip balance branch: https://github.com/WilliamWeberBerrutti/OpenHV/tree/BalanceMothership

EDIT: I created a temporary branch for this investigation, while I work on Mothership balance. It should be used instead of `BalanceMothership` one: https://github.com/WilliamWeberBerrutti/OpenHV/tree/RecentCrashesInvestigation

Commit: `d9cf88a`

Replays: [hv-2024-07-20T145128Z - Plane Crash.orarep.tar.gz](https://github.com/user-attachments/files/16321505/hv-2024-07-20T145128Z.-.Plane.Crash.orarep.tar.gz), [hv-2024-07-20T151856Z - Crash again.orarep.tar.gz](https://github.com/user-attachments/files/16321673/hv-2024-07-20T151856Z.-.Crash.again.orarep.tar.gz)

We are not sure what caused it, but Rampoina and me were playing on the map Silverman. I was Yuruki and massed planes, and when I was attacking his base it crashed (I was focusing on killing his Power Plants). We are not sure if when I attacked a Bunker, before it exploded, Rampoina sold it and made the game crash. I tried to replicate this offline and couldn't. Below is the crash log:

```
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
   at OpenRA.Traits.Target.get_CenterPosition() in ~/Git Projects/OpenHV/engine/OpenRA.Game/Traits/Target.cs:line 169
   at OpenRA.Mods.Common.Activities.FlyAttack.Tick(Actor self) in ~/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Activities/Air/FlyAttack.cs:line 167
   at OpenRA.Activities.Activity.TickOuter(Actor self) in ~/Git Projects/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in ~/Git Projects/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in ~/Git Projects/OpenHV/engine/OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in ~/Git Projects/OpenHV/engine/OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in ~/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in ~/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in ~/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in ~/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in ~/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in ~/Git Projects/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

We'll see if we can replicate the crash scenario when possible.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/14766

**Comment by Mailaender** [comment]
I assume it is related to the flying drones.

**Comment by WilliamWeberBerrutti** [comment]
The crash happened in a match where there were no drone involved, so probably something "below" them (maybe a superclass, dunno).
