### ISSUE TITLE
Crash after using Drop Pods

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1067]
Replay: [hv-2024-07-22T193028Z.orarep.tar.gz](https://github.com/user-attachments/files/16339038/hv-2024-07-22T193028Z.orarep.tar.gz)

Commit: 88ff1980b17bd0e7440e6d1b56be23281e441bd6

Branch: https://github.com/WilliamWeberBerrutti/OpenHV/tree/BalanceMothership

Log:

```
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. Abstract cell 127,19 failed to route to abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass41_0.<Heuristic>b__0(CPos cell, Boolean knownAccessible) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 1203
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 278
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 331
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 810
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 943
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTarget(Actor self, List`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 176
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 97
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass20_0.<.ctor>b__0(BlockedByActor check) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 80
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 110
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 126
   at OpenRA.Activities.Activity.TickOuter(Actor self) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in $HOME/Git Projects/OpenHV/engine/OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs:line 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in $HOME/Git Projects/OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in $HOME/Git Projects/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

**Comment by OcelotWalrus** [comment]
I happened right after a mining tower gets destroyed by pods from a droppod.

If found this https://github.com/OpenRA/OpenRA/issues/21459 related. It think it could help.

**Comment by OcelotWalrus** [comment]
Also this https://github.com/OpenRA/OpenRA/issues/20834, where it's said that it's related with an actor spawning on a cliff.

**Comment by OcelotWalrus** [comment]
The game crashes right at this moment:
![image](https://github.com/user-attachments/assets/898a322f-2e78-432a-843b-3f01d198d3b7)
