### ISSUE TITLE
SquadManagerBotModule.FindEnemies: Attempted to get trait from destroyed object

### ISSUE THREAD

**Issue by OcelotWalrus** [OpenHV/OpenHV#1076]
Logs:

```log
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (mbt 1984 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.FindEnemies(IEnumerable`1 actors, Actor sourceActor)
   at OpenRA.Mods.Common.Traits.BotModules.Squads.Squad.IsTargetValid(Actor squadUnit) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs:line 119
   at OpenRA.Mods.Common.Traits.SquadManagerBotModule.ProtectOwn(IBot bot, Actor attacker) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/BotModules/SquadManagerBotModule.cs:line 494
   at OpenRA.Mods.Common.Traits.ModularBot.<>c__DisplayClass15_0.<OpenRA.Mods.Common.Traits.INotifyDamage.Damaged>b__0() in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 115
   at OpenRA.Sync.<>c__DisplayClass14_0.<RunUnsynced>b__0() in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Sync.cs:line 172
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Sync.cs:line 203
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Sync.cs:line 173
   at OpenRA.Mods.Common.Traits.ModularBot.OpenRA.Mods.Common.Traits.INotifyDamage.Damaged(Actor self, AttackInfo e) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Player/ModularBot.cs:line 118
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Health.cs:line 204
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
   at OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/GameRules/WeaponInfo.cs:line 246
   at OpenRA.Mods.HV.Projectiles.EnergyBolt..ctor(ProjectileArgs args, EnergyBoltInfo info) in /home/rampoina/sources/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 147
   at OpenRA.Mods.HV.Projectiles.EnergyBoltInfo.Create(ProjectileArgs args) in /home/rampoina/sources/OpenHV/OpenRA.Mods.HV/Projectiles/EnergyBolt.cs:line 56
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass36_0.<FireBarrel>b__2(Int32 burst) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 346
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 342
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 287
   at OpenRA.Mods.Common.Activities.Attack.DoAttack(Actor self, AttackFrontal attack, IEnumerable`1 armaments) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Activities/Attack.cs:line 257
   at OpenRA.Mods.Common.Activities.Attack.TickAttack(Actor self, AttackFrontal attack) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Activities/Attack.cs:line 250
   at OpenRA.Mods.Common.Activities.Attack.Tick(Actor self) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Activities/Attack.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/rampoina/sources/OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/rampoina/sources/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

Replay:
(file available from 07/26/24 to 08/26/24 - expires in 30 days)

https://easyupload.io/87ts31

Version:

This crash happened on upstream commit bf23777

**Comment by OcelotWalrus** [comment]
For me it seems like the game tried to get the actor's traits to know which damage to apply to it, but it was dead:

```
at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Traits/Health.cs:line 204
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args) in /home/rampoina/sources/OpenHV/engine/OpenRA.Mods.Common/Warheads/SpreadDamageWarhead.cs:line 123
```

**Comment by Mailaender** [comment]
Looks like the fix in https://github.com/OpenRA/OpenRA/pull/21439 did not help.

**Comment by Mailaender** [comment]
The replay does not crash. Are you sure this is the right exception log?

**Comment by OcelotWalrus** [comment]
> The replay does not crash. Are you sure this is the right exception log?

It doesn't crash because I was on Rampoina's local server. Ask him for the real replay.

**Comment by WilliamWeberBerrutti** [comment]
Also you can compress the file (as .tar.gz or .zip, for instance) and send directly to GitHub. You don't have to use file hosting services.

**Comment by OcelotWalrus** [comment]
Right. I didn't thought about that.

**Comment by Rampoina** [comment]
[hv-2024-07-26T134502Z.orarep.tar.gz](https://github.com/user-attachments/files/16398373/hv-2024-07-26T134502Z.orarep.tar.gz)

**Comment by Mailaender** [comment]
That replay also does not crash.

**Comment by OcelotWalrus** [comment]
Maybe it's just a weird exception, that could have happen because of lag (as we were playing on a server).

**Comment by Mailaender** [comment]
It is a programming error and my attempts to fix it are in the wrong location.
