### ISSUE TITLE
Crash when using `DetonateWeaponPower` with `PlaceBeacon` trait

### ISSUE THREAD

**Issue by OcelotWalrus** [OpenHV/OpenHV#1149]
Tried on the PR #1116.

Log:
```log
OpenRA engine version c24913ea24583b5982a6fdc26fff6243dbab47f8
OpenRA Language: en
OpenHV mod version {DEV_VERSION}
on map ade44ec30b315af4cb08c21446899ade4ee6b99a (Duel Of The Shades by Cromha).
Date: 2024-08-14 06:56:31Z
Operating System: Linux (X64, Unix 6.9.9.200)
Runtime Version: .NET CLR 6.0.32
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.InvalidOperationException`: Image `beacon` does not have a sequence named `chrome`.
   at OpenRA.Graphics.SequenceSet.GetSequence(String image, String sequence) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Graphics/SequenceSet.cs:line 67
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Graphics/Animation.cs:line 129
   at OpenRA.Graphics.Animation.PlayRepeating(String sequenceName) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Graphics/Animation.cs:line 144
   at OpenRA.Mods.Common.Effects.Beacon..ctor(Player owner, WPos position, Int32 duration, String beaconPalette, Boolean isPlayerPalette, String beaconCollection, String beaconSequence, String arrowSprite, String circleSprite, Int32 delay) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Effects/Beacon.cs:line 50
   at OpenRA.Mods.Common.Effects.Beacon..ctor(Player owner, WPos position, Boolean isPlayerPalette, String palette, String posterCollection, String posterType, String posterPalette, String beaconSequence, String arrowSequence, String circleSequence, String clockSequence, Func`1 clockFraction, Int32 delay, Int32 duration) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Effects/Beacon.cs:line 69
   at OpenRA.Mods.HV.Traits.DetonateWeaponPower.Activate(Actor self, Order order, SupportPowerManager manager) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/OpenRA.Mods.HV/Traits/SupportPowers/DetonateWeaponPower.cs:line 110
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs:line 261
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs:line 106
   at OpenRA.Actor.ResolveOrder(Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Actor.cs:line 438
   at OpenRA.Network.UnitOrders.ResolveOrder(Order order, World world, OrderManager orderManager, Int32 clientId) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/UnitOrders.cs:line 414
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/UnitOrders.cs:line 398
   at OpenRA.Network.OrderManager.ProcessOrders() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 256
   at OpenRA.Network.OrderManager.TryTick() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 326
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

When I add a "null" sequence to the beacon, that uses the bits/null.png file, it prints out this and crashes again:

```log
OpenRA engine version c24913ea24583b5982a6fdc26fff6243dbab47f8
OpenRA Language: en
OpenHV mod version {DEV_VERSION}
on map ade44ec30b315af4cb08c21446899ade4ee6b99a (Duel Of The Shades by Cromha).
Date: 2024-08-14 06:57:30Z
Operating System: Linux (X64, Unix 6.9.9.200)
Runtime Version: .NET CLR 6.0.32
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.ArgumentNullException`: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at OpenRA.Graphics.SequenceSet.GetSequence(String image, String sequence) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Graphics/SequenceSet.cs:line 67
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Graphics/Animation.cs:line 129
   at OpenRA.Graphics.Animation.PlayFetchIndex(String sequenceName, Func`1 func) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Graphics/Animation.cs:line 190
   at OpenRA.Mods.Common.Effects.Beacon..ctor(Player owner, WPos position, Boolean isPlayerPalette, String palette, String posterCollection, String posterType, String posterPalette, String beaconSequence, String arrowSequence, String circleSequence, String clockSequence, Func`1 clockFraction, Int32 delay, Int32 duration) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Effects/Beacon.cs:line 81
   at OpenRA.Mods.HV.Traits.DetonateWeaponPower.Activate(Actor self, Order order, SupportPowerManager manager) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/OpenRA.Mods.HV/Traits/SupportPowers/DetonateWeaponPower.cs:line 110
   at OpenRA.Mods.Common.Traits.SupportPowerInstance.Activate(Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs:line 261
   at OpenRA.Mods.Common.Traits.SupportPowerManager.ResolveOrder(Actor self, Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Mods.Common/Traits/SupportPowers/SupportPowerManager.cs:line 106
   at OpenRA.Actor.ResolveOrder(Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Actor.cs:line 438
   at OpenRA.Network.UnitOrders.ResolveOrder(Order order, World world, OrderManager orderManager, Int32 clientId) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/UnitOrders.cs:line 414
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/UnitOrders.cs:line 398
   at OpenRA.Network.OrderManager.ProcessOrders() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 256
   at OpenRA.Network.OrderManager.TryTick() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 326
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in /home/lolo/Documents/vscode-cloned-repositories/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

```

**Comment by GraionDilach** [comment]
There's nothing within `DetonateWeaponPower` which differs in beacon handling compared to upstream support powers. Additionally, the beacon tags are all inherited from `SupportPowerInfo`.

These crashes should have been caught by the lint rules.

**Comment by OcelotWalrus** [comment]
It doesn't happen with other support powers, I checked everything and it was all the same everywhere. The crashes ain't caught by the lint rules.

**Comment by Mailaender** [comment]
You probably confused palette and sprite sequence while playing around in your branch.
