### ISSUE TITLE
Crash after ordering units

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1156]
Replay: [hv-2024-08-20T174409Z.orarep.tar.gz](https://github.com/user-attachments/files/16679812/hv-2024-08-20T174409Z.orarep.tar.gz)

Commit: https://github.com/WilliamWeberBerrutti/OpenHV/commit/21153d06adad93f4d5410f48bb05c06e7e201394

Branch: [RecentChanges](https://github.com/WilliamWeberBerrutti/OpenHV/tree/RecentChanges)

Log:

```
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. Cell 110,56 failed lookup for an abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass41_0.<Heuristic>b__0(CPos cell, Boolean knownAccessible) in OpenHV/engine/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 1163
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in OpenHV/engine/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 278
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindBidiPath(PathSearch first, PathSearch second) in OpenHV/engine/OpenRA.Mods.Common/Pathfinder/PathSearch.cs:line 372
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, CPos source, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in OpenHV/engine/OpenRA.Mods.Common/Pathfinder/HierarchicalPathFinder.cs:line 916
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTarget(Actor self, List`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in OpenHV/engine/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 176
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in OpenHV/engine/OpenRA.Mods.Common/Traits/World/PathFinder.cs:line 97
   at OpenRA.Mods.Common.Activities.Move.<>c__DisplayClass20_0.<.ctor>b__0(BlockedByActor check) in OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 80
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 110
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in OpenHV/engine/OpenRA.Mods.Common/Activities/Move/Move.cs:line 126
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Activities.Activity.TickChild(Actor self) in OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.AttackMoveActivity.Tick(Actor self) in OpenHV/engine/OpenRA.Mods.Common/Activities/Move/AttackMoveActivity.cs:line 80
   at OpenRA.Activities.Activity.TickOuter(Actor self) in OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 29
   at OpenRA.Actor.Tick() in OpenHV/engine/OpenRA.Game/Actor.cs:line 270
   at OpenRA.World.Tick() in OpenHV/engine/OpenRA.Game/World.cs:line 456
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in OpenHV/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.LogicTick() in OpenHV/engine/OpenRA.Game/Game.cs:line 666
   at OpenRA.Game.Loop() in OpenHV/engine/OpenRA.Game/Game.cs:line 835
   at OpenRA.Game.Run() in OpenHV/engine/OpenRA.Game/Game.cs:line 888
   at OpenRA.Game.InitializeAndRun(String[] args) in OpenHV/engine/OpenRA.Game/Game.cs:line 313
   at OpenRA.Launcher.Program.Main(String[] args) in OpenHV/engine/OpenRA.Launcher/Program.cs:line 32
```

**Comment by RoosterDragon** [comment]
This looks like a bug in `ForestLayer`.
https://github.com/OpenHV/OpenHV/blob/b2adc233fcd7ea4fca5376fcca40d15da42447c3/OpenRA.Mods.HV/Traits/World/ForestLayer.cs#L145-L156

The two `CrushableBy` methods do not agree - it looks like a conditional was inverted incorrectly. `Locomotor` uses one of these method for live crush checks, and the other one for caching purposes. If the methods do not agree, this causes `Locomotor` to have a cache that does not agree with live checks - this is a bug!
 
Later on `HierarchicalPathFinder` is helping with a path search and is asked "how do I get to this cell that I have been able to reach in my search" and on checking its internal bookeeping it is shocked: "but you cannot reach that cell!". It throws this exception whilst exclaiming "Locomotor cache? You *lied* to me!"

It looks like the first method is the intended check to me? If so, you want the following change to fix this:
```c#
bool ICrushable.CrushableBy(Actor self, Actor crusher, BitSet<CrushClass> crushClasses)
{
	return info.MunchClasses.Overlaps(crushClasses) || info.TraverseClasses.Overlaps(crushClasses);
}

LongBitSet<PlayerBitMask> ICrushable.CrushableBy(Actor self, BitSet<CrushClass> crushClasses)
{
	return info.MunchClasses.Overlaps(crushClasses) || info.TraverseClasses.Overlaps(crushClasses)
		? self.World.AllPlayersMask
		: self.World.NoPlayersMask;
}
```
