### ISSUE TITLE
Carrier logic rework?

### ISSUE THREAD

**Issue by dnqbob** [OpenHV/OpenHV#594]
To fix the [crash](https://github.com/OpenRA/OpenRA/pull/20212#issuecomment-1236483041) at upstream for carrier crash, we may need to rework the carrier logic.

But there is another way, we can give `Aircraft` an option that remove no land effect for carrier slave so land effect crash will not happen (I am still testing, no other crash so far).

Which one is better for us?

**Comment by Mailaender** [comment]
I don't get the crash here. Can you tell me how to reproduce it?

**Comment by dnqbob** [comment]
Sorry, I mean to find the solution of the carrier crash fix

**Comment by Mailaender** [comment]
We now see the crash here as well: #602 and it is clearly related. Drones are spawned from the drone carrier ship. Do you know how to trigger it quickly?

**Comment by dnqbob** [comment]
I don't know how to reproduce, the only way I have for it is to use the replay when the bug happens. 

Plus, there is some ideas to help on #602:

(1). You can try to see if https://github.com/OpenRA/OpenRA/pull/20313 fix this, via the replay from #602. 

In my test of https://github.com/OpenRA/OpenRA/issues/20370, this PR fix a related bug and surprisingly not result in replay desync.

(2).  If (1) is not working, I am afraid you may need to take https://github.com/MustaphaTR/OpenRA/commit/28467da9460623db547244da56bdf3b6db8d5ef7 and remove the "add influence" ability from all actors with `CarrierSlave`.

I have to say (2) is a temporarily way to fix the annoying crash (and I don't know if it is really the right place to fix), and it will desync the replay.

**Comment by Mailaender** [comment]
We probably want to fix https://github.com/MustaphaTR/OpenRA/pull/55 in the carrier code instead as normal aircraft landing is not affected.

**Comment by dnqbob** [comment]
@Mailaender 

> Why did you decide to make it configurable?

Becuase when I got this crash, I was thinking since the carriers logic is not doing well with influence, then I just make an option to aircraft to disable influence when aircraft landing

It also makes sense: when carrier slave enter aircraft, they should not block the cell and prevent other actors entering, especially when master is a moving actor (you block the cell that behind the moving master to land on the master). Idk if I understand "add influence" here correctly.

**Comment by dnqbob** [comment]
> We probably want to fix [MustaphaTR/OpenRA#55](https://github.com/MustaphaTR/OpenRA/pull/55) in the carrier code instead as normal aircraft landing is not affected.

yes and that is the better way

**Comment by dnqbob** [comment]
I think the problem in carrier is the `EnterCarrierMaster`, but except this I can't think of better way -- even if we create a new activity, we must use `Land` to support various land behavior in `Aircraft`, which is the directly causing of the crash because it is the only one can add influence that cannot be correctly cleaned later.

**Comment by GraionDilach** [comment]
I'm coming out from a cold - I can attempt to debug this during the weekend. I'm a bit confused about the situtation though, because when I last attempted to rewrite the carrier code (and IIRC all the current forks using carrier code includes/built upon my cleanup), I already had to partially bypass the influence checks because some of the landing opportunities weren't aligned with (sub)cells right. It is possible that one of these bypasses of mine regressed.

**Comment by dnqbob** [comment]
Nice to see you here.

There is also a possibility that it is not the fault of carrier code, because there are also 2 crashes similar to #602 (https://github.com/OpenRA/OpenRA/issues/20370 and https://github.com/OpenRA/OpenRA/pull/20376), which has the same problem: influence is not cleaned after actor's death, but they have nothing to do with the carrier code.

**Comment by darkademic** [comment]
I don't think I've seen an exception log for the carrier-specific crash, but I was able to cause a crash in basically the same way you can trigger other "reserved by dead actor" crashes.

Order the carrier to attack, then stop so the fighters return, but when they're about to land, do another attack order. Then kill all the fighters, wait for respawn, attack again, then when the new batch tries to land again it crashes.

Log:

```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (horn 77 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Game\TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.Locomotor.UpdateCellBlocking(CPos cell) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\Traits\World\Locomotor.cs:line 488
   at OpenRA.Mods.Common.Traits.Locomotor.CanMoveFreelyInto(Actor actor, CPos cell, SubCell subCell, BlockedByActor check, Actor ignoreActor) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\Traits\World\Locomotor.cs:line 230
   at OpenRA.Mods.Common.Traits.Mobile.GetAdjacentCell(CPos nextCell, Func`2 preferToAvoid) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\Traits\Mobile.cs:line 384
   at OpenRA.Mods.Common.Traits.Mobile.Nudge(Actor nudger) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\Traits\Mobile.cs:line 372
   at OpenRA.Mods.Common.ActorExts.NotifyBlocker(Actor self, IEnumerable`1 blockers) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\ActorExts.cs:line 65
   at OpenRA.Mods.Common.ActorExts.NotifyBlocker(Actor self, IEnumerable`1 positions) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\ActorExts.cs:line 75
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\Activities\Air\Land.cs:line 221
   at OpenRA.Activities.Activity.TickOuter(Actor self) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Game\Activities\Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Game\Activities\Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.Enter.Tick(Actor self) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Mods.Common\Activities\Enter.cs:line 140
   at OpenRA.Activities.Activity.TickOuter(Actor self) in J:\Modding\OpenRA\Repositories\Darkademic\CAmod\engine\OpenRA.Game\Activities\Activity.cs:line 108
```

**Comment by darkademic** [comment]
> @darkademic could [OpenRA/OpenRA#20313](https://github.com/OpenRA/OpenRA/pull/20313) or [OpenRA/OpenRA#20401](https://github.com/OpenRA/OpenRA/pull/20401) fix this?

Yea quite possibly. Now that I know how to replicate it reliably I'll try again with each of those fixes later today.

**Comment by darkademic** [comment]
Yea seems like either of those PRs fix it, can't replicate anymore after incorporating them.

**Comment by dnqbob** [comment]
so it is possible that it is the same as https://github.com/OpenRA/OpenRA/issues/20370

**Comment by Mailaender** [comment]
I looked through the carrier code and removed some unused code paths https://github.com/OpenHV/OpenHV/commit/914f10775fe61e327a420d2dd3ee5ea53cc4bf67 but did not see anything that looks bogus or even related to the crash. The drone has

https://github.com/OpenHV/OpenHV/blob/914f10775fe61e327a420d2dd3ee5ea53cc4bf67/mods/hv/rules/defaults.yaml#L310-L311

which I think is what triggers this quickly so the real issue is in `FlyIdle` or the aircraft landing code.
