### ISSUE TITLE
In-Game Menu: NullReferenceException at Player Mute CheckboxWidget

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#603]
Exit code is 1. It happened in networked games when someone pressed escape after losing IIRC.
```
Platform is Linux
Engine version is 3f106bef72dc60a99d268eb864903a63fa2be684
Runtime: .NET CLR 6.0.9
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20220918)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
Loading mod: hv
[2022-10-23T18:46:02] Game started
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym 0x1008FF2B (XF86WakeUp).
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 151 (143), X11 KeySym 0x1008FF2B (XF86WakeUp).
[2022-10-23T19:16:13] Game started
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.CheckboxWidget.Draw() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Widgets/CheckboxWidget.cs:line 67
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 479
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs:line 233
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Widgets.Widget.DrawOuter() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Widgets/Widget.cs:line 481
   at OpenRA.Game.RenderTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 733
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 841
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by Mailaender** [comment]
I can't reproduce this one, so I guess it is already solved.

**Comment by nmoskopp** [comment]
I can not reproduce it right now either, but it happened at least 3 times yesterday. It is pretty annoying.

If this is indeed fixed, which commit is the one with the fix?

**Comment by Mailaender** [comment]
Impossible to say. I checked all screens with checkboxes and none crash.

**Comment by Mailaender** [comment]
Do you remember which map was played?

**Comment by nmoskopp** [comment]
> Do you remember which map was played?
- Business as Usual
- Uneven Renumeration

**Comment by nmoskopp** [comment]
> Actually, nevermind: I know what is going on. It doesn't happen in skirmish only with human players.

So what is it that players should avoid to do?

**Comment by Mailaender** [comment]
Not pressing ESC in-game. I didn't plan for a new release because we don't really have that much new content, but I will release a hotfix shortly.
