### ISSUE TITLE
Map with multiplayer spawn outside the map crashes game

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#632]
```
Platform is Linux
Engine version is 111d9e4230978a72d2364e60236d7629080c633f
Runtime: .NET CLR 6.0.10
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221030)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	cameo-0.28: Cameo (0.28)
Loading mod: hv
/home/nmoskopp/.config/openra/maps/hv/20221030/test.oramap was updated
/home/nmoskopp/.config/openra/maps/hv/20221030/test.oramap was updated
/home/nmoskopp/.config/openra/maps/hv/20221030/test.oramap was updated
[2022-11-02T14:33:08] Game started
Exception of type `System.ArgumentException`: This frozen actor has no footprint.
Actor Name: base2
Actor Location: 94,-7
Input footprint: []
Input footprint (after shroud.Contains): []
   at OpenRA.Traits.FrozenActor..ctor(Actor actor, ICreatesFrozenActors frozenTrait, PPos[] footprint, Player viewer, Boolean startsRevealed) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/Player/FrozenActorLayer.cs:line 43
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.<>c__DisplayClass9_0.<OpenRA.Traits.INotifyCreated.Created>b__0(Player player, Int32 playerIndex) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs:line 73
   at OpenRA.Primitives.PlayerDictionary`1..ctor(World world, Func`3 valueFactory) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Primitives/PlayerDictionary.cs:line 38
   at OpenRA.Mods.Common.Traits.FrozenUnderFog.OpenRA.Traits.INotifyCreated.Created(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs:line 79
   at OpenRA.Actor.Initialize(Boolean addToWorld) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 207
   at OpenRA.Mods.Common.Traits.SpawnStartingUnits.SpawnUnitsForPlayer(World w, Player p) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/SpawnStartingUnits.cs:line 89
   at OpenRA.Mods.Common.Traits.SpawnStartingUnits.WorldLoaded(World world, WorldRenderer wr) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/SpawnStartingUnits.cs:line 71
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 288
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 203
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/UnitOrders.cs:line 154
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 168
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/Connection.cs:line 347
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by Mailaender** [comment]
This is expected behavior. The error message is a bit misleading, but I don't see any point of polishing this.

**Comment by Mailaender** [comment]
Actually, I want the linter to pick this up, which would make it impossible to start the map.

**Comment by nmoskopp** [comment]
I think the map editor should not have let me place a crashy spawn.

**Comment by nmoskopp** [comment]
`map.yaml` contains:
```
MapFormat: 12

RequiresMod: hv

Title: Name your map here

Author: Your name here

Tileset: PLANET

MapSize: 130,130

Bounds: 1,1,128,128

Visibility: Lobby

Categories: Conquest

Players:
	PlayerReference@Neutral:
		Name: Neutral
		OwnsWorld: True
		NonCombatant: True
		Faction: yi
	PlayerReference@Creeps:
		Name: Creeps
		NonCombatant: True
		Faction: yi
		Enemies: Multi0, Multi1, Multi2, Multi3, Multi4
	PlayerReference@Multi0:
		Name: Multi0
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi1:
		Name: Multi1
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi2:
		Name: Multi2
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi3:
		Name: Multi3
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi4:
		Name: Multi4
		Playable: True
		Faction: Random
		Enemies: Creeps

Actors:
	Actor0: mpspawn
		Owner: Neutral
		Location: 62,-3
	Actor1: mpspawn
		Owner: Neutral
		Location: 94,-7
	Actor2: mpspawn
		Owner: Neutral
		Location: 59,-7
	Actor3: mpspawn
		Owner: Neutral
		Location: 62,0
	Actor4: mpspawn
		Owner: Neutral
		Location: 65,-1
```

**Comment by Mailaender** [comment]
It seems you forged the map manually because by default the cordon is just one cell thick and placing it inside of that is even playable:

![image](https://user-images.githubusercontent.com/756669/199574929-17228873-3d37-4a19-a808-c685d5cf0d30.png)

**Comment by Mailaender** [comment]
Oh wait, the editor indeed allows it. Sorry. The spawn is just invisible.

**Comment by nmoskopp** [comment]
> It seems you forged the map manually

I did not; I (mis-)clicked outside the visible map area when placing a spawn.

> The spawn is just invisible.

Indeed – this makes the misclicks so punishing.
