### ISSUE TITLE
Ordering a transport air unit to pick up a vehicle crashes the game sometimes

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#636]
```
Platform is Linux
Engine version is 111d9e4230978a72d2364e60236d7629080c633f
Runtime: .NET CLR 6.0.10
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221030)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	cameo-0.28: Cameo (0.28)
Loading mod: hv
[2022-11-02T21:46:42] Game started
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 871
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 881
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Air/Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 144
   at OpenRA.Mods.Common.Activities.PickupUnit.Tick(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/PickupUnit.cs:line 116
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

I looked at the OpenRA bug tracker myself this time and found https://github.com/OpenRA/OpenRA/issues/20402 … is this the same type of crash? If so, I suggest to keep this issue open until upstream has a patch and OpenHV has updated the engine or OpenHV has a workaround.

**Comment by Mailaender** [comment]
Yes, it is the same bug. We use the same `Carryall` trait. I wasn't aware of this one.
