### ISSUE TITLE
Placing scrap with map editor crashes game when skirmish is started

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#638]
```
Platform is Linux
Engine version is 111d9e4230978a72d2364e60236d7629080c633f
Runtime: .NET CLR 6.0.10
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221030)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	cameo-0.28: Cameo (0.28)
Loading mod: hv
/home/nmoskopp/.config/openra/maps/hv/20221030/ttt.oramap was updated
[2022-11-04T17:37:44] Game started
Exception of type `System.InvalidOperationException`: TypeDictionary does not contain instance of type `OpenRA.Mods.HV.ValueInit`
   at OpenRA.ActorInitializer.Get[T](TraitInfo info) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Map/ActorInitializer.cs:line 69
   at OpenRA.Mods.HV.Traits.ScrapValue..ctor(ActorInitializer init, ScrapValueInfo info) in /home/runner/work/OpenHV/OpenHV/OpenRA.Mods.HV/Traits/ScrapValue.cs:line 31
   at OpenRA.Mods.HV.Traits.ScrapValueInfo.Create(ActorInitializer init) in /home/runner/work/OpenHV/OpenHV/OpenRA.Mods.HV/Traits/ScrapValue.cs:line 22
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 161
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/SpawnMapActors.cs:line 49
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 288
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 203
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/UnitOrders.cs:line 154
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/OrderManager.cs:line 168
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Network/Connection.cs:line 347
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by nmoskopp** [comment]
I suggest to place scrap on the shellmap as a simple regression test once this is fixed.

**Comment by SeanScherer** [comment]
Funny, I thought I had placed scrap once and can't remember their being issues.
Guess I'll go try. (though this is not exactly a high priority bug in my view...).

**Comment by nmoskopp** [comment]
> though this is not exactly a high priority bug in my view

Maybe, but it shows a lack of rigor. A simple map containing all actors could have caught it.

**Comment by SeanScherer** [comment]
"lack of rigor" ? Maybe you have different aims than what I do in making games (disclaimer: I am and have not in any way been involved in making OpenHV).
Side note - I think this sort of discussion lends itself better to other venues. (I'm the person that wrote you an email btw, in case the connection was not clear - not that I was asking for this kind of conversation :P).

**Comment by SeanScherer** [comment]
P.S. I do get the crash as well, would need to keep testing to find out which scrap is the issue (as pointed out above, unsure if that's worth it to me).

**Comment by nmoskopp** [comment]
Removing the ability to place scrap in the map editor is both the simplest and possibly the most frustrating way to work around the crash. I reported the bug because I wanted to use scrap in a map I made to create tension. This is now impossible.

**Comment by Mailaender** [comment]
The value of the scrap is determined from a percentage of the value of the unit that was destroyed. I added fallback values for pre-placed scrap: https://github.com/OpenHV/OpenHV/commit/32aebd3add69091b5059336a7ceff5d2419c0c83
