### ISSUE TITLE
Map editor crashes when loading a map with spawn points deleted and actors referencing the non-existing player

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#647]
I tried to make a mission-type map that has no multiplayer spawn points (i.e. no main base) using the map editor.

As seemed impossible to place non-neutral non-creep units without spawn points, I added spawn points, then placed units, then deleted the spawn points.

I found that the map editor crashes loading an editor-created map that has units, but no multiplayer spawn points:

```
Platform is Linux
Engine version is 111d9e4230978a72d2364e60236d7629080c633f
Runtime: .NET CLR 6.0.10
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221030)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
Loading mod: hv
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key 'Multi1' was not present in the dictionary.
   at OpenRA.Mods.Common.Traits.EditorActorLayer.WorldLoaded(World world, WorldRenderer wr) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs:line 82
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 288
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 203
   at OpenRA.Game.LoadEditor(String mapUid) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 510
   at OpenRA.Mods.HV.Widgets.Logic.CustomMainMenuLogic.<>c__DisplayClass15_0.<LoadMapIntoEditor>b__0() in /home/runner/work/OpenHV/OpenHV/OpenRA.Mods.HV/Widgets/Logic/CustomMainMenuLogic.cs:line 316
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Primitives/ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/16868

**Comment by nmoskopp** [comment]
So how do I make maps that have no spawn, but only pre-placed units?
