### ISSUE TITLE
Ordering a landed air unit to force move crashes the game sometimes

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#659]
The crash seems to be quite difficult to reproduce, but it is common enough to happen every few hours.

I have no working replay for this yet, but will report back with more details once I have one.

Below is a log for a transport dropship crashing the game on force-move.

I think it happened with elite pods too at some point.

```
; ./OpenHV-20221119-x86_64.AppImage 
Platform is Linux
Engine version is 22a42b7dc9f55c515d01109a3b5df18380f6e4b3
Runtime: .NET CLR 6.0.11
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221119)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	hv-20221119: OpenHV (20221119)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
Loading mod: hv
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
[2022-11-22T00:08:43] Game started
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
[2022-11-22T00:09:55] Game started
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
[2022-11-22T00:11:28] Game started
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
[2022-11-22T00:13:57] Game started
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
[2022-11-22T00:16:23] Game started
/home/nmoskopp/.config/openra/maps/hv/20221119/abwinter2.oramap was updated
[2022-11-22T00:18:26] Game started
[2022-11-22T00:19:07] Game started
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 871
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 881
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Air/Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
# exited 1
```

**Comment by nmoskopp** [comment]
I have a replay: [hv-2022-11-22T000159Z issue.orarep.zip](https://github.com/OpenHV/OpenHV/files/10061469/hv-2022-11-22T000159Z.issue.orarep.zip)

```
; ./OpenHV-20221119-x86_64.AppImage 
Platform is Linux
Engine version is 22a42b7dc9f55c515d01109a3b5df18380f6e4b3
Runtime: .NET CLR 6.0.11
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221119)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	hv-20221119: OpenHV (20221119)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
Loading mod: hv
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 871
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Air/Aircraft.cs:line 881
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Activities/Air/Land.cs:line 232
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
# exited 1
```

**Comment by nmoskopp** [comment]
**To reproduce, order a landed elite pod to pick up scrap.**

**Comment by Mailaender** [comment]
Looks like https://github.com/OpenRA/OpenRA/issues/20468
