### ISSUE TITLE
Mining tower resource transporter spawn can crash game

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#686]
At the top edge of the map, a mining tower can try to spawn a resource transporter out of bounds:

```
Platform is Linux
Engine version is 22a42b7dc9f55c515d01109a3b5df18380f6e4b3
Runtime: .NET CLR 6.0.11
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 20.3.5
Using default sound device
Internal mods:
	hv: OpenHV (20221119)
External mods:
	sp-release-20220702: Shattered Paradise (release-20220702)
	ra-release-20210321: Red Alert (release-20210321)
	hv-20221030: OpenHV (20221030)
	hv-20220526: OpenHV (20220526)
	sa-20210523: OpenSA (20210523)
	hv-20220918: OpenHV (20220918)
	hv-20221119: OpenHV (20221119)
	d2k-release-20210321: Dune 2000 (release-20210321)
	cnc-release-20210321: Tiberian Dawn (release-20210321)
	raplus-v.1.4.1-classicqueue: Red Alert Plus (v.1.4.1-classicqueue)
Loading mod: hv
/home/nmoskopp/.config/openra/maps/hv/20221119/d.oramap was updated
[2022-11-26T15:46:00] Game started
Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array.
   at OpenRA.Map.GetTerrainIndex(CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Map/Map.cs:line 1113
   at OpenRA.Mods.Common.Traits.Locomotor.MovementSpeedForCell(CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/World/Locomotor.cs:line 201
   at OpenRA.Mods.Common.Traits.Mobile.MovementSpeedForCell(CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Mobile.cs:line 741
   at OpenRA.Mods.Common.Traits.Mobile.LocalMove(Actor self, WPos fromPos, WPos toPos, CPos cell) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Mobile.cs:line 797
   at OpenRA.Mods.Common.Traits.Mobile.LocalMove(Actor self, WPos fromPos, WPos toPos) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Mobile.cs:line 712
   at OpenRA.Mods.Common.Traits.Mobile.ReturnToCellActivity.Tick(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Mods.Common/Traits/Mobile.cs:line 686
   at OpenRA.Activities.Activity.TickOuter(Actor self) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Activities/Activity.cs:line 108
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Traits/ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Actor.cs:line 262
   at OpenRA.World.Tick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 639
   at OpenRA.Game.LogicTick() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 654
   at OpenRA.Game.Loop() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 823
   at OpenRA.Game.Run() in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/OpenHV/OpenHV/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed
```

**Comment by SeanScherer** [comment]
I see two possible fixes: 

* Spawn the transports at the "base" (ie bottom cell of the building) rather than the top of the Mining tower (probably not preferable  due to visuals).
* Disable placing metal/ore deposits that close to the top edge of the map (no idea how/if you can do that though... - that is without touching the editors code :/ ). 

I guess what we could do in the interim is add a note for "map makers" (but I don't think there is any specific docs for them yet? Thats something I could change though :P ).

**Comment by nmoskopp** [comment]
Disabling ore placement seems like a way too complex solution. As it stands right now, resource transporters can be spawned in impassable terrain, which would also need to be detected somehow.

By the way: The best fix for the crash here would be to actually check if the placement is legal before doing it. Spawning the transport at the base of the building would greatly simplify things in that you would have to get the building out-of-bounds, so the crash would not be able to be triggered – but bounds checks are important to prevent such issues.

If the OpenRA engine was written in C, stuff like this could easily become a security vulnerability instead of a relatively harmless exception.

**Comment by SeanScherer** [comment]
I'm not going to get into this, but just re " If the OpenRA engine was written in C, ... " --> sounds like a good idea it isn't then :P .

**Comment by SeanScherer** [comment]
_"An invisible “shell” of terrain that the server can interact with but the client can not see extends around the map."_

Yeah, I was thinking something along those lines could be helpful for quite a few things. The map edge is a little bug prone in general I think (the way its set up atm) - see eg also #555 .

**Comment by nmoskopp** [comment]
>> _"An invisible “shell” of terrain that the server can interact with but the client can not see extends around the map."_
> 
> Yeah, I was thinking something along those lines could be helpful for quite a few things. The map edge is a little bug prone in general I think (the way its set up atm) - see eg also #555 .

I would not be so sure of that. In Minetest such a thing would probably not be interactable from a client in the way that you think it would be. The Minetest solution prevents the server from crashing, but to clients the area is basically the same as an area that the server has not yet sent to the client (and never will). So I doubt that you would have usability improvements from this.

Regardless, in Minetest the map edge has been carefully engineered to prevent a bunch of easy out-of-bounds issues that can happen. For example, placing something (as is the case in this issue) usually just works regardless of where you place it – because in the worst case whatever you want to place (or maybe half of it) is just outside the visible area of the map. If this were not the case, code would have to account for the map border, e.g. either figuring out where it can place things before placing them or (if the engine silently did not place stuff placed outside the visible bounds) validating that every single thing got placed before doing anything that might result in unintended consequences. This is also why silently not placing things out of bounds is probably a bad idea.

Anyways, the institutional knowledge of the Minetest approach seems to have withered to the point where some of the core developers themselves do not seem to understand the intentions of this setup. They have changed how the engine behaves at the map border for the worse in the past (despite my warnings) and will probably do it again.

In any case, I suspect that this issue exposes that the mining tower has not been properly unit tested. There are only a limited amount of map edges and corners, so one can test the code for each of them.

**Comment by SeanScherer** [comment]
_" unit tested."_

Not sure if I have "unit tests" in mind, but setting up auto-testing is something I've thought about for games I've worked on/ had in mind.

That doesn't resolve the question of who's priority setting those up is, nor your happily ignoring points regarding communication :P.
